---
title: "Correlação"
subtitle: "Introdução à correlação em Python"
author: "Renato Augusto Correa dos Santos"
date: 2025-10-19
format:
    html:
        theme: cosmo
        toc: true
        toc-depth: 2
        code-fold: true
        code-copy: true
        number-sections: true
jupyter: python3
lang: pt-BR
execute:
    echo: true
    warning: false
    error: false
---

Importando pandas:

```{python}
import pandas as pd
```


Importando dataset dos pinguins:

```{python}
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()
```

Vamos explorar relações/similaridades entre colunas do dataset.

```{python}
penguins.columns
```


Podemos calcular associações entre:
 * duas variáveis qualitativas
 * duas variáveis quantitativas
 * uma variável qualitativa e outra quantitativa

**Tabelas de dupla entrada (ou de contingência)** são usadas para resumir **variáveis qualitativas**.

Para **variáveis quantitativas**, podemos utilizar **gráficos de dispersão ou de quantis**



# Associação entre variáveis qualitativas

Algumas perguntas que podemos fazer envolvendo variaveis qualitativas.

Existe associação entre:
 * Espécie de pinguim e ilha ?
 * Ilha e sexo de pinguim ?

```{python}
penguins['species'].unique()
```

Primeiramente, vamos obter uma tabela com distribuição de frequências:

## Tabela de contingencia com as variaveis ilha e especie

Existe associação entre espécie de pinguim e ilha ?

```{python}
pd.crosstab(penguins['island'], penguins['species'])
```



```{python}
tab_contingencia = pd.crosstab(penguins['island'], penguins['species'])
print('Tabela de contingência:')
print(tab_contingencia)
```

Adicionar os valores totais das distribuições das duas variáveis.


Para uma determinada espécie, existe associação entre a ilha e o sexo? Selecionar uma unica espécie que acontece em mais de uma ilha?


```{python}
tab_contingencia = pd.crosstab(penguins['island'], penguins['sex'])
print('Tabela de contingência:')
print(tab_contingencia)
```




## Calculando frequencias relativas

Frequências relativas podem ser usadas no lugar de frequências absolutas.

Essas frequências podem ser calculadas em relação ao total ou ao número de distribuições nas linhas e nas colunas. 


```{python}
tab_freq_relativa = pd.crosstab(penguins['island'], penguins['species'], normalize='all')
print('\nFrequências relativas:')
print(tab_freq_relativa)
```




```{python}

```


## Calculando associações entre as variáveis qualitativas

Descrever a associação entre as variáveis significa conhecer o grau de dependência entre elas.


## Medidas de associação entre variáveis qualitativas

Cálculo de coeficientes de associação ou correlação.

### Valores de Qui-quadrado de Pearson

Valores maiores indicam que há associação; valores próximos de zero indicam que variáveis são indepedentes.



### 


# Associação entre variáveis quantitativas

## Gráficos de dispersão

Podem ser observadas associações lineares positivas, negativas ou a ausência de associação linear.

```{python}

```


## Medidas de associação entre variáveis quantitativas


1. Mudança nos valores para o centro da curva de dispersão
2. Ajuste na escala das variáveis, já que geralmente estão em escalas diferentes e apresentam diferentes variabilidades. (divisão de desvios pelos desvios padrões)
3. Produto das coordenadas reduzidas
4. Soma dos produtos das coordenadas
5. Cálculo da correlação, definido pela média dos produtos

Ver tabela 4.15 (Estatística Básica - Bussab e Morettin)



## Testes para o coeficiente de correlação


