<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matheus Pimenta">

<title>Dia 03 - Distribuições e Testes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="dia_03_apoio_files/libs/clipboard/clipboard.min.js"></script>
<script src="dia_03_apoio_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="dia_03_apoio_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="dia_03_apoio_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="dia_03_apoio_files/libs/quarto-html/popper.min.js"></script>
<script src="dia_03_apoio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="dia_03_apoio_files/libs/quarto-html/anchor.min.js"></script>
<link href="dia_03_apoio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="dia_03_apoio_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="dia_03_apoio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="dia_03_apoio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="dia_03_apoio_files/libs/bootstrap/bootstrap-7e1a670c3e8b405c259ac02b9fc21bd0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul class="collapse">
  <li><a href="#a-transição-da-descrição-para-a-inferência" id="toc-a-transição-da-descrição-para-a-inferência" class="nav-link active" data-scroll-target="#a-transição-da-descrição-para-a-inferência"><span class="header-section-number">1</span> A Transição da Descrição para a Inferência</a></li>
  <li><a href="#a-matemática-da-incerteza-e-a-distribuição-normal" id="toc-a-matemática-da-incerteza-e-a-distribuição-normal" class="nav-link" data-scroll-target="#a-matemática-da-incerteza-e-a-distribuição-normal"><span class="header-section-number">2</span> A Matemática da Incerteza e a Distribuição Normal</a>
  <ul class="collapse">
  <li><a href="#a-onipresença-da-curva-de-sino-gaussiana" id="toc-a-onipresença-da-curva-de-sino-gaussiana" class="nav-link" data-scroll-target="#a-onipresença-da-curva-de-sino-gaussiana"><span class="header-section-number">2.1</span> A Onipresença da Curva de Sino (Gaussiana)</a></li>
  <li><a href="#o-conceito-de-máxima-verossimilhança-mle" id="toc-o-conceito-de-máxima-verossimilhança-mle" class="nav-link" data-scroll-target="#o-conceito-de-máxima-verossimilhança-mle"><span class="header-section-number">2.2</span> O Conceito de Máxima Verossimilhança (MLE)</a></li>
  <li><a href="#implementação-computacional-e-análise-de-código-ajuste-de-distribuições" id="toc-implementação-computacional-e-análise-de-código-ajuste-de-distribuições" class="nav-link" data-scroll-target="#implementação-computacional-e-análise-de-código-ajuste-de-distribuições"><span class="header-section-number">2.3</span> Implementação Computacional e Análise de Código: Ajuste de Distribuições</a></li>
  </ul></li>
  <li><a href="#a-filosofia-e-mecânica-dos-testes-de-hipótese" id="toc-a-filosofia-e-mecânica-dos-testes-de-hipótese" class="nav-link" data-scroll-target="#a-filosofia-e-mecânica-dos-testes-de-hipótese"><span class="header-section-number">3</span> A Filosofia e Mecânica dos Testes de Hipótese</a>
  <ul class="collapse">
  <li><a href="#o-paradigma-frequentista-e-a-analogia-do-tribunal" id="toc-o-paradigma-frequentista-e-a-analogia-do-tribunal" class="nav-link" data-scroll-target="#o-paradigma-frequentista-e-a-analogia-do-tribunal"><span class="header-section-number">3.1</span> O Paradigma Frequentista e a Analogia do Tribunal</a></li>
  <li><a href="#o-limiar-de-decisão-nível-de-significância-alpha" id="toc-o-limiar-de-decisão-nível-de-significância-alpha" class="nav-link" data-scroll-target="#o-limiar-de-decisão-nível-de-significância-alpha"><span class="header-section-number">3.2</span> O Limiar de Decisão: Nível de Significância (<span class="math inline">\(\alpha\)</span>)</a></li>
  <li><a href="#comparação-de-duas-médias-o-teste-t-de-student" id="toc-comparação-de-duas-médias-o-teste-t-de-student" class="nav-link" data-scroll-target="#comparação-de-duas-médias-o-teste-t-de-student"><span class="header-section-number">3.3</span> Comparação de Duas Médias: O Teste t de Student</a></li>
  </ul></li>
  <li><a href="#análise-de-variância-anova" id="toc-análise-de-variância-anova" class="nav-link" data-scroll-target="#análise-de-variância-anova"><span class="header-section-number">4</span> Análise de Variância (ANOVA)</a>
  <ul class="collapse">
  <li><a href="#a-lógica-da-decomposição-da-variância" id="toc-a-lógica-da-decomposição-da-variância" class="nav-link" data-scroll-target="#a-lógica-da-decomposição-da-variância"><span class="header-section-number">4.1</span> A Lógica da Decomposição da Variância</a></li>
  <li><a href="#executando-one-way-anova-com-statsmodels" id="toc-executando-one-way-anova-com-statsmodels" class="nav-link" data-scroll-target="#executando-one-way-anova-com-statsmodels"><span class="header-section-number">4.2</span> Executando One-Way ANOVA com <code>statsmodels</code></a></li>
  </ul></li>
  <li><a href="#diagnóstico-do-modelo-e-a-análise-de-resíduos" id="toc-diagnóstico-do-modelo-e-a-análise-de-resíduos" class="nav-link" data-scroll-target="#diagnóstico-do-modelo-e-a-análise-de-resíduos"><span class="header-section-number">5</span> Diagnóstico do Modelo e a Análise de Resíduos</a>
  <ul class="collapse">
  <li><a href="#extração-e-teste-visual-dos-resíduos" id="toc-extração-e-teste-visual-dos-resíduos" class="nav-link" data-scroll-target="#extração-e-teste-visual-dos-resíduos"><span class="header-section-number">5.1</span> Extração e Teste Visual dos Resíduos</a></li>
  <li><a href="#testes-formais-shapiro-wilk-e-homocedasticidade" id="toc-testes-formais-shapiro-wilk-e-homocedasticidade" class="nav-link" data-scroll-target="#testes-formais-shapiro-wilk-e-homocedasticidade"><span class="header-section-number">5.2</span> Testes Formais: Shapiro-Wilk e Homocedasticidade</a></li>
  </ul></li>
  <li><a href="#post-hoc-analysis-tukey-hsd" id="toc-post-hoc-analysis-tukey-hsd" class="nav-link" data-scroll-target="#post-hoc-analysis-tukey-hsd"><span class="header-section-number">6</span> Post-Hoc Analysis (Tukey HSD)</a>
  <ul class="collapse">
  <li><a href="#execução-com-statsmodels" id="toc-execução-com-statsmodels" class="nav-link" data-scroll-target="#execução-com-statsmodels"><span class="header-section-number">6.1</span> Execução com <code>statsmodels</code></a></li>
  <li><a href="#interpretação-detalhada-da-matriz-de-decisão" id="toc-interpretação-detalhada-da-matriz-de-decisão" class="nav-link" data-scroll-target="#interpretação-detalhada-da-matriz-de-decisão"><span class="header-section-number">6.2</span> Interpretação Detalhada da Matriz de Decisão</a></li>
  <li><a href="#visualização-dos-intervalos" id="toc-visualização-dos-intervalos" class="nav-link" data-scroll-target="#visualização-dos-intervalos"><span class="header-section-number">6.3</span> Visualização dos Intervalos</a></li>
  </ul></li>
  <li><a href="#two-way-anova-e-o-conceito-de-interação" id="toc-two-way-anova-e-o-conceito-de-interação" class="nav-link" data-scroll-target="#two-way-anova-e-o-conceito-de-interação"><span class="header-section-number">7</span> Two-Way ANOVA e o Conceito de Interação</a>
  <ul class="collapse">
  <li><a href="#modelagem-matemática-da-interação" id="toc-modelagem-matemática-da-interação" class="nav-link" data-scroll-target="#modelagem-matemática-da-interação"><span class="header-section-number">7.1</span> Modelagem Matemática da Interação</a></li>
  <li><a href="#implementação-em-python" id="toc-implementação-em-python" class="nav-link" data-scroll-target="#implementação-em-python"><span class="header-section-number">7.2</span> Implementação em Python</a></li>
  <li><a href="#visualizando-interações-o-interaction-plot" id="toc-visualizando-interações-o-interaction-plot" class="nav-link" data-scroll-target="#visualizando-interações-o-interaction-plot"><span class="header-section-number">7.3</span> Visualizando Interações: O “Interaction Plot”</a></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">8</span> Conclusão</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Dia 03 - Distribuições e Testes</h1>
<p class="subtitle lead">Introdução à Estatística com Python</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Matheus Pimenta </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">11 de fevereiro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="a-transição-da-descrição-para-a-inferência" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> A Transição da Descrição para a Inferência</h1>
<p>A jornada pelo universo da ciência de dados e da estatística computacional atinge, neste terceiro dia, um ponto de inflexão crítico. Até o momento, as ferramentas exploradas — manipulação de DataFrames, visualização de dados e estatística descritiva — serviram a um propósito fundamental, porém limitado: o de resumir e descrever o que já foi observado. A média de uma coluna em um dataset ou o histograma de uma variável são retratos do passado, fotografias estáticas de um conjunto finito de observações. No entanto, o verdadeiro poder da ciência reside não apenas em catalogar o que aconteceu, mas em generalizar essas observações para o desconhecido, prevendo comportamentos futuros ou inferindo propriedades de populações inteiras que jamais poderemos medir em sua totalidade. Este é o domínio da <strong>Inferência Estatística</strong>.</p>
<p>A inferência estatística é, em sua essência, uma ponte epistemológica construída sobre a matemática da probabilidade. Ela nos permite atravessar o abismo entre a amostra (o subconjunto de dados que possuímos, frequentemente imperfeito e limitado) e a população (a verdade universal subjacente que buscamos compreender). O processo não é isento de riscos; ao tentar dizer algo sobre o todo baseando-nos apenas em uma parte, aceitamos a inevitabilidade da incerteza. A estatística não elimina essa incerteza, mas fornece uma estrutura rigorosa para quantificá-la, gerenciá-la e utilizá-la como ferramenta de decisão.</p>
<hr>
</section>
<section id="a-matemática-da-incerteza-e-a-distribuição-normal" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> A Matemática da Incerteza e a Distribuição Normal</h1>
<p>Antes de podermos testar qualquer hipótese sobre o mundo, precisamos de uma linguagem para descrever a forma como os dados se dispersam aleatoriamente. Essa linguagem é dada pelas <strong>Distribuições de Probabilidade</strong>. Embora existam dezenas de distribuições teóricas para modelar desde o tempo de falha de componentes eletrônicos (Exponencial, Weibull) até contagens de eventos raros (Poisson), uma distribuição reina soberana na estatística clássica: a Distribuição Normal, ou Gaussiana.</p>
<section id="a-onipresença-da-curva-de-sino-gaussiana" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="a-onipresença-da-curva-de-sino-gaussiana"><span class="header-section-number">2.1</span> A Onipresença da Curva de Sino (Gaussiana)</h2>
<p>A centralidade da Distribuição Normal na estatística inferencial não é um acidente histórico, nem apenas uma conveniência matemática. Ela é fundamentada no Teorema Central do Limite (TCL). O TCL estabelece que, sob condições bastante gerais, a soma (ou a média) de um grande número de variáveis aleatórias independentes e identicamente distribuídas tenderá a seguir uma distribuição normal, independentemente da forma da distribuição original dessas variáveis. Isso significa que, mesmo que os dados individuais de uma população sejam estranhos, assimétricos ou complexos, as médias calculadas a partir de amostras dessa população se comportarão de maneira previsível, moldadas pela curva em sino.</p>
<p>Matematicamente, a Função Densidade de Probabilidade (PDF - Probability Density Function) de uma variável aleatória contínua <span class="math inline">\(X\)</span> que segue uma distribuição normal é definida por dois parâmetros fundamentais: a média (<span class="math inline">\(\mu\)</span>), que localiza o centro da distribuição, e o desvio padrão (<span class="math inline">\(\sigma\)</span>), que determina sua dispersão ou largura. A fórmula elegante que descreve essa curva é:</p>
<p><span class="math display">\[f(x | \mu, \sigma) = \frac{1}{\sqrt{2\pi\sigma^2}} e^{ -\frac{(x-\mu)^2}{2\sigma^2} }\]</span></p>
<p>Para compreender verdadeiramente o que o computador calcula quando pedimos o ajuste de uma normal, precisamos dissecar essa equação termo a termo:</p>
<ol type="1">
<li><p><strong>O Fator de Normalização (<span class="math inline">\(\frac{1}{\sqrt{2\pi\sigma^2}}\)</span>):</strong> A integral de qualquer função de densidade de probabilidade sobre todo o espaço real deve ser igual a <span class="math inline">\(1\)</span> (100% de probabilidade). Sem esse termo constante, a área sob a exponencial seria <span class="math inline">\(\sqrt{2\pi\sigma^2}\)</span>. Ao dividirmos por esse valor, garantimos que a curva represente uma distribuição de probabilidade válida.</p></li>
<li><p><strong>O Núcleo Exponencial (<span class="math inline">\(e^{ -\frac{(x-\mu)^2}{2\sigma^2} }\)</span>):</strong> Este é o motor da distribuição. O termo <span class="math inline">\((x-\mu)^2\)</span> no numerador do expoente representa a distância quadrática de um valor <span class="math inline">\(x\)</span> em relação à média <span class="math inline">\(\mu\)</span>.</p>
<ul>
<li>Como o expoente é negativo, quanto maior a distância <span class="math inline">\(|x-\mu|\)</span>, menor o valor da função. Isso cria o formato de sino, com o pico em <span class="math inline">\(\mu\)</span> e caudas que decaem para zero em ambas as direções.</li>
<li>O termo <span class="math inline">\(2\sigma^2\)</span> no denominador do expoente atua como um fator de escala. Se <span class="math inline">\(\sigma\)</span> (desvio padrão) for grande, o denominador é grande, o que amortece o efeito da distância <span class="math inline">\((x-\mu)^2\)</span>. Isso faz com que a curva decaia mais lentamente, resultando em uma distribuição “gorda” e dispersa. Se <span class="math inline">\(\sigma\)</span> for pequeno, o decaimento é rápido, gerando um pico agudo e estreito.</li>
</ul></li>
</ol>
</section>
<section id="o-conceito-de-máxima-verossimilhança-mle" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="o-conceito-de-máxima-verossimilhança-mle"><span class="header-section-number">2.2</span> O Conceito de Máxima Verossimilhança (MLE)</h2>
<p>Quando coletamos dados no mundo real, como o comprimento das pétalas de uma flor Iris versicolor, não recebemos junto o manual de instruções com os valores verdadeiros de <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>. Temos apenas os dados <span class="math inline">\(x_1, x_2,..., x_n\)</span>. Como escolhemos os “melhores” parâmetros para descrever esses dados? A resposta reside no método da Estimação de Máxima Verossimilhança (MLE - Maximum Likelihood Estimation).</p>
<p>A intuição do MLE é inverter a lógica probabilística padrão. Normalmente, dada uma distribuição (ex: Normal com média 0 e desvio 1), calculamos a probabilidade de observar um dado <span class="math inline">\(x\)</span>. No MLE, dado que já observamos os dados, perguntamos: “Qual distribuição (quais parâmetros <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>) torna a observação desses dados específicos o evento mais provável possível?”.</p>
<p>Formalmente, para uma amostra de observações independentes, a função de Verossimilhança <span class="math inline">\(L(\theta)\)</span> é o produto das densidades de probabilidade individuais:</p>
<p><span class="math display">\[L(\mu, \sigma | x_1,..., x_n) = \prod_{i=1}^{n} f(x_i | \mu, \sigma) = \prod_{i=1}^{n} \frac{1}{\sqrt{2\pi\sigma^2}} e^{ -\frac{(x_i-\mu)^2}{2\sigma^2} }\]</span></p>
<p>Em termos computacionais, multiplicar muitas probabilidades (valores entre 0 e 1) resulta rapidamente em underflow numérico (o computador arredonda para zero). Por isso, algoritmos como os do scipy trabalham com o Log-Likelihood (<span class="math inline">\(\mathcal{L}\)</span>), transformando o produtório em um somatório, que é matematicamente mais tratável e computacionalmente estável:</p>
<p><span class="math display">\[\mathcal{L}(\mu, \sigma) = \ln L(\mu, \sigma) = \sum_{i=1}^{n} \ln f(x_i | \mu, \sigma)\]</span></p>
<p>Para encontrar os estimadores ótimos, derivamos essa função em relação a <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span> e igualamos a zero.</p>
<ul>
<li>Para a média <span class="math inline">\(\mu\)</span>, o estimador MLE é intuitivo: <span class="math inline">\(\hat{\mu}_{MLE} = \frac{1}{n}\sum_{i=1}^n x_i\)</span>. É a média aritmética simples.</li>
<li>Para a variância <span class="math inline">\(\sigma^2\)</span>, entretanto, surge uma divergência crucial. O estimador MLE é:</li>
</ul>
<p><span class="math display">\[\hat{\sigma}^2_{MLE} = \frac{1}{n} \sum_{i=1}^{n} (x_i - \bar{x})^2\]</span></p>
<p>Note o denominador <span class="math inline">\(n\)</span>. Em cursos introdutórios de estatística, aprendemos exaustivamente a usar <span class="math inline">\(n-1\)</span> para calcular a variância amostral. Por que o MLE usa <span class="math inline">\(n\)</span>? O estimador MLE é, tecnicamente, enviesado (biased). Ele tende a subestimar a variância verdadeira da população porque utiliza a média amostral (<span class="math inline">\(\bar{x}\)</span>) no cálculo, que se ajusta aos dados específicos da amostra melhor do que a média verdadeira da população (<span class="math inline">\(\mu\)</span>) faria. Os dados estão sempre “mais próximos” da sua própria média amostral do que da média populacional real.</p>
<p>Para corrigir esse viés, utiliza-se a Correção de Bessel, trocando <span class="math inline">\(n\)</span> por <span class="math inline">\(n-1\)</span>. Isso é fundamental em amostras pequenas. Bibliotecas focadas em análise de dados como o <code>pandas</code> aplicam a correção de Bessel por padrão (<code>ddof=1</code>), enquanto bibliotecas focadas em ajuste probabilístico puro como o scipy.stats aplicam o MLE estrito (<code>ddof=0</code> ou denominador <span class="math inline">\(n\)</span>).</p>
</section>
<section id="implementação-computacional-e-análise-de-código-ajuste-de-distribuições" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="implementação-computacional-e-análise-de-código-ajuste-de-distribuições"><span class="header-section-number">2.3</span> Implementação Computacional e Análise de Código: Ajuste de Distribuições</h2>
<p>Vamos concretizar essa teoria analisando o comprimento das pétalas da espécie Iris Versicolor utilizando Python. O objetivo é duplo: visualizar a distribuição empírica e ajustar uma curva teórica Normal usando MLE.</p>
<p>Carregamento e Preparação dos Dados:</p>
<div id="4a18493c" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuração estética dos gráficos</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregamento do dataset Iris embutido no Seaborn</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>df_iris <span class="op">=</span> sns.load_dataset(<span class="st">'iris'</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtragem: Selecionando apenas a espécie Versicolor e a variável petal_length</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>data_versicolor <span class="op">=</span> df_iris[df_iris[<span class="st">'species'</span>] <span class="op">==</span> <span class="st">'versicolor'</span>][<span class="st">'petal_length'</span>]</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização inicial das primeiras linhas</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Amostra dos dados (Versicolor - Petal Length):"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_versicolor.head())</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Amostra dos dados (Versicolor - Petal Length):
50    4.7
51    4.5
52    4.9
53    4.0
54    4.6
Name: petal_length, dtype: float64</code></pre>
</div>
</div>
<p>Ajuste da Distribuição (MLE) com <code>scipy.stats</code>:</p>
<p>O código a seguir utiliza a função <code>stats.norm.fit</code>. É importante entender o que esta função executa nos bastidores. Ela não está “adivinhando”; ela está executando a otimização dos parâmetros da Equação da Verossimilhança discutida acima.</p>
<div id="5a46582a" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Passo 1: Ajuste de Máxima Verossimilhança</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A função fit() retorna uma tupla (loc, scale)</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Para a normal: loc = média, scale = desvio padrão</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>mu_mle, std_mle <span class="op">=</span> stats.norm.fit(data_versicolor)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">--- Parâmetros Estimados via MLE (scipy) ---"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Média (mu): </span><span class="sc">{</span>mu_mle<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Desvio Padrão (sigma): </span><span class="sc">{</span>std_mle<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Nota: O scipy usa denominador 'n' (enviesado) para o desvio padrão."</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Passo 2: Comparação com Estatística Descritiva Padrão (Pandas)</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>mean_pandas <span class="op">=</span> data_versicolor.mean()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>std_pandas <span class="op">=</span> data_versicolor.std() <span class="co"># Padrão do pandas é ddof=1</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">--- Parâmetros Estimados via Pandas (Bessel's Correction) ---"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Média: </span><span class="sc">{</span>mean_pandas<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Desvio Padrão: </span><span class="sc">{</span>std_pandas<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Nota: O pandas usa denominador 'n-1' (não-enviesado)."</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Cálculo manual da diferença para evidenciar a matemática</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(data_versicolor)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>diferenca_std <span class="op">=</span> std_pandas <span class="op">-</span> std_mle</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Diferença nos Desvios Padrões (n-1 vs n): </span><span class="sc">{</span>diferenca_std<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
--- Parâmetros Estimados via MLE (scipy) ---
Média (mu): 4.2600
Desvio Padrão (sigma): 0.4652
Nota: O scipy usa denominador 'n' (enviesado) para o desvio padrão.

--- Parâmetros Estimados via Pandas (Bessel's Correction) ---
Média: 4.2600
Desvio Padrão: 0.4699
Nota: O pandas usa denominador 'n-1' (não-enviesado).

Diferença nos Desvios Padrões (n-1 vs n): 0.0047</code></pre>
</div>
</div>
<p>Análise das Saídas e Implicações: Ao executar este código, observaremos que as médias (<code>mu_mle</code> e <code>mean_pandas</code>) são idênticas. O estimador da média no MLE é não-enviesado. Contudo, os desvios padrões divergirão.</p>
<ul>
<li>O <code>std_mle</code> será ligeiramente menor. Isso confirma que o MLE subestima a dispersão.</li>
<li>O <code>std_pandas</code> será maior, pois dividir por <span class="math inline">\(n-1\)</span> (49, no caso de <span class="math inline">\(n=50\)</span> observações da Versicolor) resulta em um valor maior do que dividir por <span class="math inline">\(n\)</span> (50).</li>
</ul>
<p>Visualização Gráfica da Aderência:</p>
<p>Para validar se a suposição de normalidade faz sentido, sobrepomos a curva teórica (gerada com os parâmetros MLE) ao histograma dos dados reais.</p>
<div id="ce95c6c6" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando a figura</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Histograma dos dados reais (densidade)</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>sns.histplot(data_versicolor, kde<span class="op">=</span><span class="va">False</span>, stat<span class="op">=</span><span class="st">"density"</span>, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">"skyblue"</span>, label<span class="op">=</span><span class="st">"Dados Reais (Histograma)"</span>, bins<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Gerando a curva teórica Normal</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Criamos um eixo x fictício variando entre min e max dos dados</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>xmin, xmax <span class="op">=</span> plt.xlim()</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>x_axis <span class="op">=</span> np.linspace(xmin, xmax, <span class="dv">100</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos a PDF teórica para cada ponto x usando os parâmetros mu e std do MLE</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>p_axis <span class="op">=</span> stats.norm.pdf(x_axis, mu_mle, std_mle)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotando a curva</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>plt.plot(x_axis, p_axis, <span class="st">'k'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Normal Ajustada (MLE)'</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Ajuste de Distribuição Normal: Iris Versicolor (Petal Length)'</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Comprimento da Pétala (cm)'</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Densidade de Probabilidade'</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="dia_03_apoio_files/figure-html/cell-4-output-1.png" width="671" height="458" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Neste gráfico, a linha preta representa o modelo idealizado. As barras azuis são a realidade ruidosa. A “bondade do ajuste” (<em>goodness-of-fit</em>) pode ser avaliada visualmente (a curva segue a forma das barras?) ou por testes estatísticos que veremos adiante (Shapiro-Wilk).</p>
</section>
</section>
<section id="a-filosofia-e-mecânica-dos-testes-de-hipótese" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> A Filosofia e Mecânica dos Testes de Hipótese</h1>
<p>Uma vez que conseguimos descrever os dados através de parâmetros de distribuições, podemos avançar para a Tomada de Decisão. A ciência raramente se contenta em dizer “a média é 4.2”. Ela pergunta: “A média é 4.2 por acaso, ou isso reflete um efeito real do tratamento?”. Entramos no território dos Testes de Hipótese.</p>
<section id="o-paradigma-frequentista-e-a-analogia-do-tribunal" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="o-paradigma-frequentista-e-a-analogia-do-tribunal"><span class="header-section-number">3.1</span> O Paradigma Frequentista e a Analogia do Tribunal</h2>
<p>A estrutura lógica do teste de hipótese frequentista (Neyman-Pearson/Fisher) é, muitas vezes, contra-intuitiva. Ela opera por contradição. Não provamos que algo é verdadeiro; tentamos mostrar que a alternativa é implausível. A melhor analogia pedagógica para entender esse processo é o Julgamento Criminal.</p>
<ol type="1">
<li>A <strong>Hipótese Nula (<span class="math inline">\(H_0\)</span>) = A Presunção de Inocência</strong>: Ao iniciar um julgamento, o réu é considerado inocente. Não importa o quão suspeito ele pareça, o estado inicial do sistema é “nada aconteceu”, “não há crime”, “não há diferença entre os grupos”. O ônus da prova recai sobre a acusação. Na estatística, <span class="math inline">\(H_0\)</span> postula que qualquer diferença observada nos dados é mero fruto do acaso (ruído amostral).</li>
<li>Os <strong>Dados = A Evidência</strong>: Coletamos evidências (amostras). Calculamos uma estatística de teste (como um valor <span class="math inline">\(t\)</span> ou <span class="math inline">\(F\)</span>), que resume a força dessa evidência contra a inocência do réu.</li>
<li>O <strong>Valor-p (P-value) = O Nível de Surpresa</strong>: Esta é a parte mais mal compreendida. O p-valor responde à seguinte pergunta condicional: “Se o réu fosse realmente inocente (<span class="math inline">\(H_0\)</span> verdadeira), qual seria a probabilidade de encontrarmos uma evidência tão incriminatória (ou mais) quanto esta, puramente por coincidência?”.
<ul>
<li><strong>P-valor alto (ex: 0.30)</strong>: Significa que a evidência é comum. Se o réu for inocente, evidências assim aparecem 30% das vezes. Não há surpresa. O veredito é “Inocente” (falhamos em rejeitar <span class="math inline">\(H_0\)</span>).</li>
<li><strong>P-valor baixo (ex: 0.001)</strong>: É altamente improvável. Se o réu fosse inocente, uma evidência dessa magnitude surgiria apenas 1 vez em 1000 julgamentos. Isso é suspeito demais. A “surpresa” é tão grande que abandonamos a crença na inocência. O veredito é “Culpado” (rejeitamos <span class="math inline">\(H_0\)</span>).</li>
</ul></li>
</ol>
<p>Importante: O p-valor <strong>NÃO</strong> é a probabilidade de o réu ser inocente. É a probabilidade da evidência, dada a inocência. <span class="math inline">\(P(Dados | H_0) \neq P(H_0 | Dados)\)</span>.</p>
</section>
<section id="o-limiar-de-decisão-nível-de-significância-alpha" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="o-limiar-de-decisão-nível-de-significância-alpha"><span class="header-section-number">3.2</span> O Limiar de Decisão: Nível de Significância (<span class="math inline">\(\alpha\)</span>)</h2>
<p>Para emitir um veredito, precisamos de um padrão de prova. Em um tribunal civil, pode ser “preponderância da evidência”. Em um criminal, é “além de qualquer dúvida razoável”. Na estatística, definimos esse padrão a priori como o Nível de Significância (<span class="math inline">\(\alpha\)</span>), tipicamente 0.05 (5%).</p>
<ul>
<li>O <span class="math inline">\(\alpha\)</span> é o risco máximo que aceitamos correr de condenar um inocente (Erro Tipo I).</li>
<li>Se <span class="math inline">\(p\text{-valor} &lt; \alpha\)</span>, consideramos o resultado “estatisticamente significativo”.</li>
</ul>
</section>
<section id="comparação-de-duas-médias-o-teste-t-de-student" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="comparação-de-duas-médias-o-teste-t-de-student"><span class="header-section-number">3.3</span> Comparação de Duas Médias: O Teste t de Student</h2>
<p>O teste mais fundamental da inferência é a comparação de dois grupos. Para isso, utilizamos o Teste t, desenvolvido por William Gosset. Gosset trabalhava na cervejaria Guinness e lidava com pequenas amostras de cevada. Ele percebeu que, ao usar o desvio padrão da amostra (<span class="math inline">\(s\)</span>) em vez do populacional (<span class="math inline">\(\sigma\)</span>) para calcular o erro padrão, a distribuição das médias não era perfeitamente Normal, mas tinha caudas mais “pesadas” (mais incerteza). Essa nova distribuição foi batizada de <strong>t de Student</strong>.</p>
<p>A estatística t é, essencialmente, uma medida de sinal-ruído:</p>
<p><span class="math display">\[t = \frac{\text{Diferença entre Médias (Sinal)}}{\text{Variabilidade dos Dados (Ruído)}} = \frac{\bar{x}_1 - \bar{x}_2}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}\]</span></p>
<p><strong>O Problema das Variâncias Desiguais (Teste t de Welch)</strong></p>
<p>A fórmula acima (t de Student clássico) assume que as variâncias dos dois grupos são idênticas (Homocedasticidade). Mas e se compararmos a massa corporal de pinguins machos e fêmeas, e a variabilidade dos machos for muito maior? O teste clássico falha, aumentando o erro Tipo I.</p>
<p>A solução moderna é o <strong>Teste t de Welch</strong>. Ele não assume variâncias iguais. Ele ajusta os <strong>Graus de Liberdade (<span class="math inline">\(df\)</span>)</strong> usando a equação de Welch-Satterthwaite, resultando frequentemente em um número fracionário de graus de liberdade. Na prática estatística contemporânea com Python, recomenda-se usar o teste de Welch por padrão, a menos que haja uma forte razão teórica para assumir variâncias iguais.</p>
<p><strong>Estudo de Caso com Python: Dimorfismo Sexual em Pinguins</strong></p>
<p>Vamos investigar se há uma diferença significativa na massa corporal (<em>body_mass_g</em>) entre pinguins machos e fêmeas da espécie Gentoo.</p>
<p>Hipóteses:</p>
<ul>
<li><p><span class="math inline">\(H_0: \mu_{machos} = \mu_{fêmeas}\)</span> (As médias são iguais).</p></li>
<li><p><span class="math inline">\(H_1: \mu_{machos} \neq \mu_{fêmeas}\)</span> (Há diferença significativa).</p></li>
</ul>
<div id="eb85eb5c" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregamento do dataset Penguins</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>df_penguins <span class="op">=</span> sns.load_dataset(<span class="st">'penguins'</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtragem de dados: Selecionando espécie Gentoo</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>gentoo_data <span class="op">=</span> df_penguins[df_penguins[<span class="st">'species'</span>] <span class="op">==</span> <span class="st">'Gentoo'</span>]</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Separação dos grupos e limpeza de NaNs (passo crucial)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># O ttest falhará se houver dados faltantes</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>mass_males <span class="op">=</span> gentoo_data[gentoo_data[<span class="st">'sex'</span>] <span class="op">==</span> <span class="st">'Male'</span>][<span class="st">'body_mass_g'</span>].dropna()</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>mass_females <span class="op">=</span> gentoo_data[gentoo_data[<span class="st">'sex'</span>] <span class="op">==</span> <span class="st">'Female'</span>][<span class="st">'body_mass_g'</span>].dropna()</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Tamanho da amostra (Machos): </span><span class="sc">{</span><span class="bu">len</span>(mass_males)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Tamanho da amostra (Fêmeas): </span><span class="sc">{</span><span class="bu">len</span>(mass_females)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Execução do Teste t de Welch</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># O parâmetro equal_var=False ativa a correção de Welch para variâncias desiguais</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>t_stat, p_val <span class="op">=</span> ttest_ind(mass_males, mass_females, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Resultados do Teste t de Welch ---"</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estatística t: </span><span class="sc">{</span>t_stat<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Valor-p: </span><span class="sc">{</span>p_val<span class="sc">:.20f}</span><span class="ss">"</span>) <span class="co"># Formatação para revelar a magnitude real</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Decisão baseada em alpha = 0.05</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> p_val <span class="op">&lt;</span> alpha:</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Decisão: Rejeitar a Hipótese Nula (H0)."</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Há evidência estatística de diferença de massa entre os sexos."</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Decisão: Falha em rejeitar H0. Não há evidência suficiente."</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Tamanho da amostra (Machos): 61
Tamanho da amostra (Fêmeas): 58

--- Resultados do Teste t de Welch ---
Estatística t: 14.7614
Valor-p: 0.00000000000000000000

Decisão: Rejeitar a Hipótese Nula (H0).
Há evidência estatística de diferença de massa entre os sexos.</code></pre>
</div>
</div>
<p><strong>Interpretação dos Resultados:</strong> Ao rodar este código, é provável que você encontre um valor-p na ordem de <span class="math inline">\(10^{-20}\)</span> ou menor.</p>
<ol type="1">
<li><p><strong>Estatística t positiva (ex: 14.7):</strong> O numerador da fórmula (<span class="math inline">\(\bar{x}_{macho} - \bar{x}_{fêmea}\)</span>) foi positivo, indicando que a média dos machos é substancialmente maior.</p></li>
<li><p><strong>Valor-p minúsculo:</strong> A probabilidade de observar uma diferença de massa tão grande (ou maior) puramente por acaso, se machos e fêmeas tivessem a mesma média populacional, é virtualmente zero.</p></li>
<li><p><strong>Conclusão Biológica:</strong> Existe um dimorfismo sexual significativo em pinguins Gentoo, com machos sendo mais pesados.</p></li>
</ol>
</section>
</section>
<section id="análise-de-variância-anova" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Análise de Variância (ANOVA)</h1>
<p>E se quisermos comparar três grupos? Por exemplo, o comprimento da pétala entre as espécies <em>Setosa, Versicolor</em> e <em>Virginica</em>.</p>
<p>A intuição inicial seria fazer três testes t: (Setosa vs Versicolor), (Versicolor vs Virginica), (Setosa vs Virginica).Por que isso é errado?Cada teste t carrega um risco de 5% (<span class="math inline">\(\alpha=0.05\)</span>) de erro Tipo I (falso positivo). Ao realizarmos múltiplos testes independentes, esses riscos se acumulam. Para 3 testes, a probabilidade de cometer pelo menos um erro sobe para <span class="math inline">\(1 - (0.95)^3 \approx 14.3\%\)</span>. Isso é chamado de <strong>Inflação do Erro Familiar</strong>.</p>
<p>A solução é a <strong>ANOVA (Analysis of Variance)</strong>. A ANOVA permite testar globalmente se alguma das médias difere, mantendo o <span class="math inline">\(\alpha\)</span> controlado em 5%, independentemente do número de grupos.</p>
<section id="a-lógica-da-decomposição-da-variância" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="a-lógica-da-decomposição-da-variância"><span class="header-section-number">4.1</span> A Lógica da Decomposição da Variância</h2>
<p>O nome “Análise de Variância” pode parecer paradoxal quando estamos interessados em médias. No entanto, a ANOVA opera comparando duas fontes de variação nos dados:</p>
<ol type="1">
<li><strong>Variação Entre Grupos (Between-Group Variance):</strong> Mede o quanto as médias de cada grupo (<span class="math inline">\(\bar{x}_j\)</span>) se afastam da média global de todos os dados (<span class="math inline">\(\bar{x}_{..}\)</span>). Se os grupos forem muito diferentes (ex: Setosa tem pétalas minúsculas e Virginica enormes), essa variação será alta. Este é o nosso <strong>SINAL</strong> (o efeito da espécie).</li>
</ol>
<p><span class="math display">\[SS_{Between} = \sum_{j=1}^{k} n_j (\bar{x}_j - \bar{x}_{..})^2\]</span></p>
<ol start="2" type="1">
<li><strong>Variação Dentro dos Grupos (Within-Group Variance):</strong> Mede o quanto cada observação individual (<span class="math inline">\(x_{ij}\)</span>) varia em relação à média do seu próprio grupo (<span class="math inline">\(\bar{x}_j\)</span>). Isso representa a variabilidade natural, diferenças genéticas individuais, erro de medição. Este é o nosso <strong>RUÍDO</strong>.</li>
</ol>
<p><span class="math display">\[SS_{Within} = \sum_{j=1}^{k} \sum_{i=1}^{n_j} (x_{ij} - \bar{x}_j)^2\]</span></p>
<p>A Estatística F é, portanto, a razão Sinal/Ruído, ponderada pelos graus de liberdade:</p>
<p><span class="math display">\[F = \frac{\text{Quadrado Médio Entre (MS}_B)}{\text{Quadrado Médio Dentro (MS}_W)} = \frac{SS_{Between} / (k-1)}{SS_{Within} / (N-k)}\]</span></p>
<p>Se <span class="math inline">\(F\)</span> for significativamente maior que 1, a variação provocada pelo “tratamento” (Espécie) é maior do que a variação aleatória. Isso sugere que as espécies são distintas.</p>
</section>
<section id="executando-one-way-anova-com-statsmodels" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="executando-one-way-anova-com-statsmodels"><span class="header-section-number">4.2</span> Executando One-Way ANOVA com <code>statsmodels</code></h2>
<p>Vamos utilizar o dataset Iris. Optaremos pela biblioteca <code>statsmodels</code> em vez de <code>scipy</code> porque ela gera a Tabela ANOVA clássica, que detalha a decomposição da variância, fundamental para uma análise profissional.</p>
<p><strong>A Sintaxe de Fórmula do Statsmodels:</strong> O <code>statsmodels</code> adota uma sintaxe inspirada na linguagem R, o que facilita a definição de modelos. A string <code>'petal_length ~ C(species)'</code> deve ser lida como: “Modele a variável petal_length em função da variável categórica species”. O <code>C()</code> força a interpretação da variável como categórica, embora para strings o pandas já faça isso automaticamente.</p>
<div id="70d7cdaf" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Passo 1: Definição e Ajuste do Modelo OLS (Ordinary Least Squares)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>model_anova <span class="op">=</span> ols(<span class="st">'petal_length ~ C(species)'</span>, data<span class="op">=</span>df_iris).fit()</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Passo 2: Geração da Tabela ANOVA</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># typ=2 refere-se ao Tipo II Sum of Squares (veremos a seguir)</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>anova_table <span class="op">=</span> sm.stats.anova_lm(model_anova, typ<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"--- Tabela ANOVA: Comprimento da Pétala por Espécie ---"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anova_table)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>--- Tabela ANOVA: Comprimento da Pétala por Espécie ---
              sum_sq     df            F        PR(&gt;F)
C(species)  437.1028    2.0  1180.161182  2.856777e-91
Residual     27.2226  147.0          NaN           NaN</code></pre>
</div>
</div>
<p>Interpretação da Tabela de Saída:</p>
<p>A saída será uma tabela (DataFrame) contendo colunas cruciais. Vamos analisar uma saída típica para este dataset:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fonte</th>
<th>sum_sq</th>
<th>df</th>
<th>F</th>
<th>PR(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C(species)</td>
<td>437.10</td>
<td>2.0</td>
<td>1180.16</td>
<td>2.85e-91</td>
</tr>
<tr class="even">
<td>Residual</td>
<td>27.22</td>
<td>147.0</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>
<ol type="1">
<li><p><strong>df (Degrees of Freedom):</strong></p>
<ul>
<li><strong>C(species):</strong> <span class="math inline">\(k-1 = 3-1 = 2\)</span>. Temos 3 espécies, logo 2 graus de liberdade para o efeito. (Imagine que se você sabe a média global e as médias de 2 espécies, a terceira é fixada; por isso perde-se 1 grau de liberdade).</li>
<li><strong>Residual:</strong> <span class="math inline">\(N - k = 150 - 3 = 147\)</span>. São os graus de liberdade restantes para estimar o erro.</li>
</ul></li>
<li><p><strong>sum_sq (Soma dos Quadrados):</strong></p>
<ul>
<li>A variação explicada pelas espécies (437.10) é massivamente maior que a variação residual (27.22). Isso já é um forte indício de efeito.</li>
</ul></li>
<li><p><strong>F (Estatística F):</strong> O valor 1180.16 significa que o sinal é mais de mil vezes mais forte que o ruído de fundo.</p></li>
<li><p><strong>PR(&gt;F):</strong> O valor-p é <span class="math inline">\(2.85 \times 10^{-91}\)</span>. Este número é tão absurdamente pequeno que podemos afirmar com certeza quase absoluta: as médias de comprimento de pétala não são iguais entre as espécies. Rejeitamos <span class="math inline">\(H_0\)</span>.</p></li>
</ol>
<p>Nota sobre <code>typ=2</code> (Soma de Quadrados Tipo II): O argumento <code>typ</code> define como a variância é calculada em designs desbalanceados ou com múltiplos fatores.</p>
<ul>
<li><p><strong>Tipo I (Sequencial):</strong> A ordem das variáveis importa. A variância é atribuída ao primeiro fator, depois o que sobra ao segundo. Perigoso em dados desbalanceados.</p></li>
<li><p><strong>Tipo II (Parcial/Hierárquico):</strong> Calcula o efeito de um fator assumindo que todos os outros fatores principais estão no modelo, mas ignora interações. É o padrão recomendado para testes de efeitos principais quando não há interações significativas.</p></li>
<li><p><strong>Tipo III (Marginal):</strong> Necessário quando há interações, mas exige codificação de contrastes ortogonais para ser válido. Para uma One-Way ANOVA (só um fator), os resultados são idênticos, mas usar <code>typ=2</code> cria um hábito robusto para modelos futuros mais complexos.</p></li>
</ul>
</section>
</section>
<section id="diagnóstico-do-modelo-e-a-análise-de-resíduos" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Diagnóstico do Modelo e a Análise de Resíduos</h1>
<p>Um dos erros mais graves e comuns em análises estatísticas é testar as premissas (como normalidade) nos dados brutos.</p>
<p><strong>Atenção:</strong> A ANOVA não exige que a variável resposta (<code>petal_length</code>) seja normal globalmente. Ela exige que os <strong>RESÍDUOS</strong> (a parte do erro, <span class="math inline">\(\epsilon\)</span>) sejam normais dentro de cada grupo.</p>
<p>Se plotarmos o histograma de <code>petal_length</code> de todas as íris juntas, veremos uma distribuição bimodal ou trimodal (vários picos). Isso não invalida a ANOVA. O que deve ser normal é o que “sobra” depois que subtraímos a média de cada espécie dos seus dados.</p>
<section id="extração-e-teste-visual-dos-resíduos" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="extração-e-teste-visual-dos-resíduos"><span class="header-section-number">5.1</span> Extração e Teste Visual dos Resíduos</h2>
<p>O objeto <code>model_anova</code> que criamos anteriormente armazena os resíduos no atributo <code>.resid</code>.</p>
<div id="f11642a0" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Acessando os resíduos do modelo</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>residuals <span class="op">=</span> model_anova.resid</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Configurando plotagem lado a lado</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Histograma dos Resíduos</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>sns.histplot(residuals, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>ax[<span class="dv">0</span>], color<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"Histograma dos Resíduos"</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">"Valor do Resíduo"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Q-Q Plot (Quantile-Quantile Plot)</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compara os quantis dos resíduos com os quantis teóricos de uma Normal</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>sm.qqplot(residuals, line<span class="op">=</span><span class="st">'45'</span>, fit<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>ax[<span class="dv">1</span>])</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"Q-Q Plot dos Resíduos"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="dia_03_apoio_files/figure-html/cell-7-output-1.png" width="753" height="368" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretação do Q-Q Plot:</strong> O Q-Q plot é a ferramenta de diagnóstico mais poderosa. No eixo X temos onde os dados deveriam estar se fossem perfeitamente normais. No eixo Y, onde eles realmente estão.</p>
<ul>
<li><p>Se os pontos azuis caírem exatamente sobre a linha vermelha de 45 graus, a normalidade é perfeita.</p></li>
<li><p>Se os pontos nas pontas se curvarem para fora da linha, isso indica “caudas pesadas” (outliers ou curtose excessiva).</p></li>
<li><p>Se os pontos formarem um “S”, a distribuição pode ser assimétrica. No caso do dataset Iris, é comum observar leves desvios nas pontas, mas se a massa central dos dados segue a linha, a ANOVA geralmente é robusta o suficiente para manter sua validade.</p></li>
</ul>
</section>
<section id="testes-formais-shapiro-wilk-e-homocedasticidade" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="testes-formais-shapiro-wilk-e-homocedasticidade"><span class="header-section-number">5.2</span> Testes Formais: Shapiro-Wilk e Homocedasticidade</h2>
<p>Além da inspeção visual, aplicamos testes estatísticos formais.</p>
<ol type="1">
<li><p><strong>Shapiro-Wilk:</strong> Testa a normalidade dos resíduos. (<span class="math inline">\(H_0\)</span>: Resíduos são normais).</p></li>
<li><p><strong>Levene:</strong> Testa a homogeneidade das variâncias (Homocedasticidade) entre os grupos. É preferível ao teste de Bartlett quando os dados não são perfeitamente normais. (<span class="math inline">\(H_0\)</span>: Variâncias são iguais).</p></li>
</ol>
<div id="817fbcee" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de Normalidade nos Resíduos</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>shapiro_stat, shapiro_p <span class="op">=</span> stats.shapiro(residuals)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Teste Shapiro-Wilk: W=</span><span class="sc">{</span>shapiro_stat<span class="sc">:.4f}</span><span class="ss">, p=</span><span class="sc">{</span>shapiro_p<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de Homogeneidade de Variância (Levene)</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Precisamos passar os grupos separadamente</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>setosa <span class="op">=</span> df_iris[df_iris[<span class="st">'species'</span>]<span class="op">==</span><span class="st">'setosa'</span>][<span class="st">'petal_length'</span>]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>versicolor <span class="op">=</span> df_iris[df_iris[<span class="st">'species'</span>]<span class="op">==</span><span class="st">'versicolor'</span>][<span class="st">'petal_length'</span>]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>virginica <span class="op">=</span> df_iris[df_iris[<span class="st">'species'</span>]<span class="op">==</span><span class="st">'virginica'</span>][<span class="st">'petal_length'</span>]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>levene_stat, levene_p <span class="op">=</span> stats.levene(setosa, versicolor, virginica)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Teste de Levene: W=</span><span class="sc">{</span>levene_stat<span class="sc">:.4f}</span><span class="ss">, p=</span><span class="sc">{</span>levene_p<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Teste Shapiro-Wilk: W=0.9811, p=0.0368
Teste de Levene: W=19.4803, p=0.0000</code></pre>
</div>
</div>
<p><strong>Decisão e Remediação:</strong></p>
<ul>
<li><p>Se Shapiro-Wilk tiver <span class="math inline">\(p &lt; 0.05\)</span>, a normalidade é violada. Porém, com <span class="math inline">\(N=150\)</span>, a ANOVA é robusta devido ao Teorema Central do Limite.</p></li>
<li><p>Se Levene tiver <span class="math inline">\(p &lt; 0.05\)</span>, a suposição de variâncias iguais é violada (Heterocedasticidade). Isso é mais grave.30 No dataset Iris, é comum que a variância das pétalas varie entre espécies. Se a violação for severa, deve-se considerar a <strong>ANOVA de Welch</strong> (disponível na biblioteca <code>pingouin</code> como <code>pingouin.welch_anova</code>) ou transformações de dados (Log, Raiz Quadrada).</p></li>
</ul>
</section>
</section>
<section id="post-hoc-analysis-tukey-hsd" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Post-Hoc Analysis (Tukey HSD)</h1>
<p>A ANOVA nos informou que existe uma diferença entre as espécies (<span class="math inline">\(p \approx 0\)</span>). Mas onde? Será que Setosa é diferente de Versicolor? Versicolor de Virginica? A ANOVA é um teste “Omnibus” (global). Para investigar os pares específicos, precisamos de testes <strong>Post-Hoc</strong>.</p>
<p>Não podemos simplesmente rodar múltiplos testes t agora, pelo mesmo motivo da inflação de erro discutida antes. Precisamos de um teste que corrija o valor-p para múltiplas comparações. O padrão-ouro para comparações par-a-par quando as variâncias são iguais é o <strong>Teste de Tukey HSD (Honest Significant Difference)</strong>.</p>
<p>O Tukey HSD calcula uma estatística <span class="math inline">\(q\)</span> (Studentized Range Statistic) baseada na diferença entre a maior e a menor média, ajustada pelo erro padrão. Ele constrói intervalos de confiança simultâneos para todas as diferenças.</p>
<section id="execução-com-statsmodels" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="execução-com-statsmodels"><span class="header-section-number">6.1</span> Execução com <code>statsmodels</code></h2>
<div id="32ec012c" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.multicomp <span class="im">import</span> pairwise_tukeyhsd</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># O Tukey exige os dados empilhados (endog) e os identificadores de grupo</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>tukey <span class="op">=</span> pairwise_tukeyhsd(endog<span class="op">=</span>df_iris[<span class="st">'petal_length'</span>],</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                          groups<span class="op">=</span>df_iris[<span class="st">'species'</span>],</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                          alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"--- Resultados do Teste de Tukey HSD ---"</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tukey)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>--- Resultados do Teste de Tukey HSD ---
   Multiple Comparison of Means - Tukey HSD, FWER=0.05   
=========================================================
  group1     group2   meandiff p-adj lower  upper  reject
---------------------------------------------------------
    setosa versicolor    2.798   0.0 2.5942 3.0018   True
    setosa  virginica     4.09   0.0 3.8862 4.2938   True
versicolor  virginica    1.292   0.0 1.0882 1.4958   True
---------------------------------------------------------</code></pre>
</div>
</div>
</section>
<section id="interpretação-detalhada-da-matriz-de-decisão" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="interpretação-detalhada-da-matriz-de-decisão"><span class="header-section-number">6.2</span> Interpretação Detalhada da Matriz de Decisão</h2>
<p>A saída do <code>pairwise_tukeyhsd</code> é rica em informações. Vamos analisar uma saída hipotética típica para estes dados:</p>
<section id="resultados-do-teste-de-tukey-hsd" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="resultados-do-teste-de-tukey-hsd"><span class="header-section-number">6.2.1</span> Resultados do Teste de Tukey HSD</h3>
<p><em>Multiple Comparison of Means – Tukey HSD (FWER = 0.05)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>group1</th>
<th>group2</th>
<th>meandiff</th>
<th>p-adj</th>
<th>lower</th>
<th>upper</th>
<th>reject</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>setosa</td>
<td>versicolor</td>
<td>2.798</td>
<td>0.000</td>
<td>2.5942</td>
<td>3.0018</td>
<td>Sim</td>
</tr>
<tr class="even">
<td>setosa</td>
<td>virginica</td>
<td>4.090</td>
<td>0.000</td>
<td>3.8862</td>
<td>4.2938</td>
<td>Sim</td>
</tr>
<tr class="odd">
<td>versicolor</td>
<td>virginica</td>
<td>1.292</td>
<td>0.000</td>
<td>1.0882</td>
<td>1.4958</td>
<td>Sim</td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>meandiff:</strong> A diferença simples entre as médias (<span class="math inline">\(\mu_{group2} - \mu_{group1}\)</span>). Ex: Versicolor tem pétalas, em média, 2.798 cm maiores que Setosa.</p></li>
<li><p><strong>p-adj:</strong> O valor-p corrigido. Se fosse um teste t simples, esse valor seria ainda menor, mas o Tukey “penaliza” a significância para evitar falsos positivos.</p></li>
<li><p><strong>lower / upper:</strong> O Intervalo de Confiança de 95% para a diferença real.</p>
<ul>
<li>Se o intervalo <strong>não contiver o zero</strong> (ex: vai de 2.59 a 3.00, ambos positivos), temos certeza estatística de que a diferença existe. Se o intervalo fosse de -0.5 a +0.5, o zero (nenhuma diferença) seria uma possibilidade plausível.</li>
</ul></li>
<li><p><strong>reject:</strong> A conclusão final. True significa “Rejeitar <span class="math inline">\(H_0\)</span> de que as médias são iguais”. Neste caso, todas as espécies são diferentes entre si.</p></li>
</ul>
</section>
</section>
<section id="visualização-dos-intervalos" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="visualização-dos-intervalos"><span class="header-section-number">6.3</span> Visualização dos Intervalos</h2>
<p>Uma imagem vale por mil tabelas. O método <code>plot_simultaneous</code> desenha os intervalos de confiança das médias. Grupos cujos intervalos não se sobrepõem (considerando as barras de erro projetadas) são estatisticamente diferentes.</p>
<div id="06dca96b" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> tukey.plot_simultaneous(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">"Comprimento da Pétala (cm)"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    ylabel<span class="op">=</span><span class="st">"Espécie"</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustando o tamanho da figura</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>fig.figure.set_size_inches(<span class="dv">6</span>, <span class="dv">4</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Intervalos de Confiança de Tukey (95%)"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="dia_03_apoio_files/figure-html/cell-10-output-1.png" width="561" height="368" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="two-way-anova-e-o-conceito-de-interação" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Two-Way ANOVA e o Conceito de Interação</h1>
<p>O mundo raramente é explicado por apenas uma causa. Frequentemente, múltiplos fatores atuam simultaneamente sobre uma variável resposta. Mais interessante ainda, esses fatores podem <strong>interagir</strong>.</p>
<p><strong>O que é Interação?</strong> Uma interação ocorre quando o efeito de um fator depende do nível de outro fator.</p>
<ul>
<li><p>Exemplo sem interação: Pinguins machos são 500g mais pesados que fêmeas em todas as espécies.</p></li>
<li><p>Exemplo com interação: Pinguins machos são 200g mais pesados na espécie Adelie, mas 1000g mais pesados na espécie Gentoo. Aqui, o “efeito do sexo” depende da “espécie”.</p></li>
</ul>
<p>Para modelar isso, usamos a <strong>Two-Way ANOVA</strong> (ANOVA de Duas Vias). Voltaremos ao dataset Penguins para examinar como <code>body_mass_g</code> é afetado por <code>species</code> e <code>sex</code>.</p>
<section id="modelagem-matemática-da-interação" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="modelagem-matemática-da-interação"><span class="header-section-number">7.1</span> Modelagem Matemática da Interação</h2>
<p>O modelo linear se expande para incluir termos extras:</p>
<p><span class="math display">\[Y_{ijk} = \mu + \alpha_i (\text{Espécie}) + \beta_j (\text{Sexo}) + (\alpha\beta)_{ij} (\text{Interação}) + \epsilon_{ijk}\]</span></p>
<p>O termo <span class="math inline">\((\alpha\beta)_{ij}\)</span> captura a “diferença da diferença”.</p>
</section>
<section id="implementação-em-python" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="implementação-em-python"><span class="header-section-number">7.2</span> Implementação em Python</h2>
<p>Na fórmula do <code>statsmodels</code>, o símbolo <code>*</code> (asterisco) indica “multiplicação de fatores”, ou seja, inclui os efeitos principais E a interação. Se usássemos <code>+</code>, teríamos apenas os efeitos principais (modelo aditivo).</p>
<div id="6868a260" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregando dataset penguins e removendo NaNs relevantes</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>df_penguins_clean <span class="op">=</span> df_penguins.dropna(subset<span class="op">=</span>[<span class="st">'body_mass_g'</span>, <span class="st">'species'</span>, <span class="st">'sex'</span>])</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustando o modelo com interação</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 'body_mass_g ~ C(species) * C(sex)' expande para:</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># species + sex + species:sex</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>model_2way <span class="op">=</span> ols(<span class="st">'body_mass_g ~ C(species) * C(sex)'</span>, data<span class="op">=</span>df_penguins_clean).fit()</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabela ANOVA (Tipo II é adequado aqui)</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>anova_2way <span class="op">=</span> sm.stats.anova_lm(model_2way, typ<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"--- Two-Way ANOVA: Massa Corporal ~ Espécie * Sexo ---"</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anova_2way)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>--- Two-Way ANOVA: Massa Corporal ~ Espécie * Sexo ---
                         sum_sq     df           F         PR(&gt;F)
C(species)         1.434016e+08    2.0  749.015666  8.144406e-123
C(sex)             3.709026e+07    1.0  387.459976   1.902273e-57
C(species):C(sex)  1.676557e+06    2.0    8.756997   1.973489e-04
Residual           3.130263e+07  327.0         NaN            NaN</code></pre>
</div>
</div>
<p><strong>Análise da Tabela Resultante:</strong> Você verá uma linha extra: <code>C(species):C(sex)</code>.</p>
<ol type="1">
<li><p><strong>C(species):</strong> Testa se as espécies têm massas diferentes (ignorando sexo). Provavelmente significativo.</p></li>
<li><p><strong>C(sex):</strong> Testa se sexos têm massas diferentes (ignorando espécie). Provavelmente significativo.</p></li>
<li><p><strong>C(species):C(sex):</strong> Testa a interação.</p>
<ul>
<li>Se <code>PR(&gt;F)</code> &lt; 0.05, a interação é significativa. Isso muda tudo. Não podemos mais dizer simplesmente “Machos são maiores”. Temos que dizer “Machos são maiores, mas a magnitude dessa diferença varia conforme a espécie”.</li>
</ul></li>
</ol>
</section>
<section id="visualizando-interações-o-interaction-plot" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="visualizando-interações-o-interaction-plot"><span class="header-section-number">7.3</span> Visualizando Interações: O “Interaction Plot”</h2>
<p>A melhor forma de comunicar uma interação é visualmente. Usaremos a função <code>interaction_plot</code> do <code>statsmodels</code> ou um <code>pointplot</code> do seaborn. Se as linhas que conectam as médias forem paralelas, não há interação. Se elas divergirem ou se cruzarem (“Cross-over interaction”), a interação é forte.</p>
<div id="e9f73ede" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.factorplots <span class="im">import</span> interaction_plot</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Criando gráfico de interação</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> interaction_plot(x<span class="op">=</span>df_penguins_clean[<span class="st">'species'</span>], </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                       trace<span class="op">=</span>df_penguins_clean[<span class="st">'sex'</span>], </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                       response<span class="op">=</span>df_penguins_clean[<span class="st">'body_mass_g'</span>], </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                       colors<span class="op">=</span>[<span class="st">'red'</span>, <span class="st">'blue'</span>], markers<span class="op">=</span>[<span class="st">'o'</span>, <span class="st">'s'</span>])</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Gráfico de Interação: Efeito da Espécie e Sexo na Massa Corporal"</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Massa Corporal Média (g)"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="dia_03_apoio_files/figure-html/cell-12-output-1.png" width="613" height="457" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Neste gráfico, se observarmos que a distância vertical entre a linha vermelha (Fêmeas) e azul (Machos) é muito maior na categoria “Gentoo” do que nas outras, isso visualiza a interação significativa que a tabela ANOVA detectou. Isso sugere que o dimorfismo sexual é evolutivamente mais pronunciado nos pinguins Gentoo.</p>
</section>
</section>
<section id="conclusão" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusão</h1>
<p>Neste terceiro dia, cruzamos a fronteira crítica da ciência de dados. Deixamos de ser meros contadores de histórias do passado (estatística descritiva) para nos tornarmos investigadores do desconhecido (inferência).</p>
<p>Dominamos a Distribuição Normal e o método MLE, compreendendo as sutilezas do viés nos estimadores de variância. Aplicamos o Teste t de Welch, reconhecendo que a suposição de variâncias iguais é frequentemente irrealista. Escalamos nossa análise para a ANOVA, aprendendo a decompor a variância em Sinal e Ruído, e a diagnosticar a saúde do modelo através dos Resíduos. Finalmente, refinamos nossas conclusões com testes Post-Hoc (Tukey) e modelamos a complexidade do mundo real através de Interações.</p>
<p>A estatística computacional com Python nos dá o poder de processar gigabytes de dados em milissegundos, mas é o entendimento filosófico e matemático detalhado aqui — o significado de um p-valor, a natureza de um grau de liberdade, a geometria da soma dos quadrados — que impede que transformemos esse poder em conclusões equivocadas. Lembre-se sempre: o código roda o modelo, mas é você quem valida a verdade.</p>
<p>Uso de Inteligência Artificial: Material com exemplos criados com gemini e revisado pelo autor.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>